### ISSUE TITLE
g:localvimrc_persistence_file might end up empty if partition is full

### ISSUE THREAD

**Issue by blueyed** [embear/vim-localvimrc#28]
It just happened to me that my home partition ran full, and this caused the file storing the persistent choices (`g:localvimrc_persistence_file`) to end up empty.

It would be nice if vim-localvimrc would handle this better, e.g. by writing it to a temporary file first and then moving this one.

Also, currently the return code of `writefile()` is not being checked at all.

**Comment by embear** [comment]
I added this tin commit 513369243a0bf87e7508643cccf352dfd093f35b. This should resolve this issue.

**Comment by blueyed** [comment]
Thanks!

**Comment by blueyed** [comment]
Unfortunately this causes problems with "sudo vim".. see #30.
