### ISSUE TITLE
Add a warning about how to use this with Janus?

### ISSUE THREAD

**Issue by trodrigues** [embear/vim-localvimrc#32]
Hi there,

I'm not sure this is something you'd want to do, but even if not it can be logged here even as a closed issue for anyone who happens to come across this problem.

I use https://github.com/carlhuda/janus with vim, and when I started using localvimrc I wanted to add the option to make the decision persistent. I tried it out at first, as well as the sandbox and the whitelist and couldn't get it to work.

After a few tries I thought that something else could be interfering with it, so I decided to add it to the .vimrc.before file, which Janus provides. This fixed the problem.

I'm not entirely sure why this happens, and if someone could shed some light here that would be great, but it does fix the problem.

My suggestion would be to add a tip about this to the readme, or possibly a suggestion of things that could interfere with this.

**Comment by embear** [comment]
I don't think it is a good idea to document problems causes by third party software. This is either a bug in Janus or missing in the documentation there.
If I document this in localvimrc then I need to track Janus and change documentation if the behavior of Janus changes.

**Comment by trodrigues** [comment]
I understand that and it's fair enough. I guess they could also say it doesn't matter for them because it's a plugin it's not part of Janus. In any case, I guess the existence of this issue can help anyone who searches for it. Thanks for the reply!
