### ISSUE TITLE
Would like to have a file's modeline override what is in .lvimrc

### ISSUE THREAD

**Issue by yrro** [embear/vim-localvimrc#33]
If I have `set ts=8 sts=4 sw=4 et` in a project's `.lvimrc` file, then editing the projects' Makefiles becomes annoying, since make insists that the lines for recipes begin with a tab character.

I would like for the modeline (e.g., `# vim: ts=4 sts=0 sw=4 noet`) in a file to override the settings from the `.lvimrc`.

**Comment by embear** [comment]
This would mean to reimplement the modeline functionality because localvimrc runs after modelines and just sources the .lvimrc files.

Another possibility to get the above behavior is to use the filetype in the .lvimrc file:

``` {vim}
if &ft == "make"
  ts=4 sts=0 sw=4 noet
else
  ts=8 sts=4 sw=4 et
endif
```

Would this solve your problem?

**Comment by yrro** [comment]
That's a great suggestion, thanks!
