### ISSUE TITLE
How to reload the .lvimrc file through a specific function or event?

### ISSUE THREAD

**Issue by symbolix** [embear/vim-localvimrc#34]
Hi,

I would like to have a variable in my .lvimrc file located in the root of my project that has a variable, let's say, a variable that sets a command like this:

    g:my_variable = "testPython.py -my-args"

Let's assume that this is something I execute in a tmux session to test things. So I would like to be able to update that variable at any time, to, let's say, something like this:

    g:my_variable = "testPython.py --with-aFuture"

And then when I call the function that executes my command, obviously I would like to refresh that variable.

Is there a way to force a refresh on the .lvimrc with a function? or attach it to a custom event? (I cannot think of a custom event that I can attach to a function like `executeCommand()`

Thanks.

**Comment by embear** [comment]
I'm not sure if I understand correctly. So here my answer (possibly not the answer to your question :-)

The .lvimrc file is loaded on the `BufWinEnter` event. So every time the buffer is displayed in a new window the file is realoded. There is a variable called `g:localvimrc_event` that you can change in your .vimrc to `CursorHold` for example. So every time you stop to type for `updatetime` the reloading is executed. The variable `g:localvimrc_event` takes a list of coma separated events if you wish reloading for different events.
But keep in mind that there might be some severe performance impact. Thats why `BufWinEnter` is used as default.

**Comment by symbolix** [comment]
Hi,

Thanks. I have already set this behaviour up and it works. Thank you very much.
