### ISSUE TITLE
Reload .lvimrc

### ISSUE THREAD

**Issue by alexandrelucchesi** [embear/vim-localvimrc#38]
Hi, is it possible to reload the .lvimrc file without having to restart Vim?

**Comment by embear** [comment]
The plugin sources the .lvimrc files for the `BufWinEnter` autocommand. Quoting
the documentation:

```
After a buffer is displayed in a window. This can be when the buffer is loaded
(after processing the modelines) or when a hidden buffer is displayed in
a window (and is no longer hidden).
Does not happen for :split without arguments, since you keep editing the same
buffer, or ":split" with a file that's already open in a window, because it
re-uses an existing buffer. But it does happen for a ":split" with the name of
the current buffer, since it reloads that buffer.
```

If you wish to change this behavior you can select another set of events using
the global variable `g:localvimrc_event`. For example:

```.viml
let g:localvimrc_event = [ "BufEnter", "WinEnter", "TabEnter" ]
```

Additionally I added a command `LocalVimRc` command to force reloading (9122390a10420006314ddf999a3effdd83ccfc3b).
