### ISSUE TITLE
Error with Sandbox

### ISSUE THREAD

**Issue by carlitux** [embear/vim-localvimrc#40]
I am getting this all the time

localvimrc: unable to use 'sandbox' for

**Comment by embear** [comment]
Hi,

it seems you are trying to modify an option ilike `makeprg` that can't be modified in sandbox and you have enabled `g:localvimrc_sandbox`. `g:localvimrc_sandbox` is set to `1` by default for safety so no one can do anything harmful to you just by adding a `.lvimrc` to his repository for example.

Does this explain the problem you described?

**Comment by carlitux** [comment]
That is the only line I have on localvimrc

nnoremap <leader>r :!npm test <CR>

**Comment by embear** [comment]
I should have mentioned to read `:he sandbox`

```
These items are not allowed in the sandbox:
    ....
        - defining or changing mapping, autocommands, functions, user commands
    ....
```

So, if you really want to use this you need to disable the sandbox feature in your vimrc using

```
let g:localvimrc_sandbox = 0
```

**Comment by embear** [comment]
No feedback, so this issue seems to be resolved. If not, feel free to reopen
