### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by aemonge** [embear/vim-localvimrc#41]
I'm trying to `au BufRead,BufNewFile,BufReadPost *.html set filetype=javascript` but I really don't know how to do it in the `_vimrc_local.vim` file. I've also tryied to do it in a `_vimrc_local.html` file, but seams not to work.

**Comment by embear** [comment]
I'm not really understanding what you are trying to do. I suspect you want to set the `filetype` to `javascript` for files contained in a specific directory/tree and matching `*.html`. To achieve this just add a file named `.lvimrc` to this directory/tree containing theses lines:

``` {viml}
if expand("<afile>:e") ==? 'html'
  set filetype=javascript
endif

```

If this is not the answer to your question please go into more detail...

**Comment by aemonge** [comment]
That's exactly what I meant !!! Thank you so very much !!!
