### ISSUE TITLE
Ordering of files incorrect when using symlinks

### ISSUE THREAD

**Issue by caipre** [embear/vim-localvimrc#42]
I have a project with the following lvimrc files:

```
/home/nick/project/.lvimrc -> /home/nick/dotfiles/project/lvimrc
/home/nick/project/foo/bar/.lvimrc
```

When building `l:rcfiles`, it seems that symlinks are resolved before sorting such that my root-level lvimrc file is sourced after the subdirectory-level file. Since my nested lvimrc file only exists to override options from the root-level file, having the ordering wrong makes the nested file useless.

I can use `g:localvimrc_reverse` to work around this, but it's a misuse of the setting.

**Comment by embear** [comment]
I can reproduce the problem and will fix it very soon. Problem is that I want to save the choice about loading a file when `g:localvimrc_ask` is set to 1 for the absolute path.

**Comment by embear** [comment]
Could you please test the latest version?

**Comment by caipre** [comment]
Seems to be working, thank you very much!
