### ISSUE TITLE
How do I disable searching lvimrc in the file tree?

### ISSUE THREAD

**Issue by talha131** [embear/vim-localvimrc#51]
**Case 1**
I have a `.lvimrc` in root of my project `~/project/.lvimrc`. I open Vim from root of the project and the plugin loads the file. Which is the perfect behaviour.

**Case 2**
On the other hand, if I change directory to `~/project/child/` and open Vim there. The plugin searches upward and finds and load `.lvimrc` file.

In case 2, I want to disable searching upward. I want plugin to search just in the current directory. How do I disable "search upward through the file tree" feature of the plugin?

Thank you

**Comment by talha131** [comment]
@embear I have opened a PT that adds the feature. Kindly merge it if you deem it fit.

**Comment by embear** [comment]
closed by 476e0ea29cfbe8cdfa88f7099f814fd477935ddc and/or aaea27fe897edbfb0c5f71ef0ac02489f4bcfefa
