### ISSUE TITLE
Windows 10 issue

### ISSUE THREAD

**Issue by BotWhisperer** [embear/vim-localvimrc#53]
Hi,
I am using your plugin on Windows 10 (yeah, I know :( ).  And it pops up the confirmation dialog on every file open, even if in the same directory.  The dialog also doesn't accept 'y' or 'yes' -- it re-displays the dialog.  It will only disappear with ENTER.  My .lvimrc is a couple of directories up the tree (root of the project).  This is probably pilot error, but help is appreciated.

My need for this plugin is (at least initially), to reset the ctags, and NERDTree bookmarks.  
I will attach my .lvimrc and _vimrc

[lvimrc.txt](https://github.com/embear/vim-localvimrc/files/834658/lvimrc.txt)
[vimrc.txt](https://github.com/embear/vim-localvimrc/files/834661/vimrc.txt)

It will also sometimes display this as well -- usually after the first dialog is closed:

![image](https://cloud.githubusercontent.com/assets/24319374/23807060/40f247a0-0592-11e7-89a1-1f460d34b7d4.png)

**Comment by embear** [comment]
This is an intented behavior. Please read about g:localvimrc_sandbox in the manual.
