### ISSUE TITLE
Vimball installs README.md and RELEASE.md into ~/.vim

### ISSUE THREAD

**Issue by mrubli** [embear/vim-localvimrc#54]
I don't think the README.md and RELEASE.md files should be installed into the ~/.vim directory when using the Vimball installation since that might conflict with other plugins. Perhaps they should go into a different directory or be omitted altogether?

**Comment by embear** [comment]
You are right. As I am using pathogen as package manager there never was a problem with that. I think the same applies for other package managers and the new _pack_ feature of vim.

For future releases I will exclude the two files from vimball. Command in `RELEASE.md` is already changed.
