### ISSUE TITLE
persistent decisions should include cryptographically secure hash of the rc file

### ISSUE THREAD

**Issue by marak8** [embear/vim-localvimrc#60]
Currently the `~/.localvimrc_persistent` file contains

    /home/user/projectdir/.lvimrc|Y|Y|14rw-r--r--1515086833

It contains the rc file path and its metadata. I haven't looked at the source code yet but I assume that the metadata are used to detect changes to the rc file. I think that's a weak check. All that is needed is assurance that the sourced file is the same as when it was sourced for the first time and for that a cryptographic hash of the file is enough. I propose the following format:

    version:metadata filename

which would look like this for the previous case

    2:flags=YY:hash=037f1086f7296e09c28b7f7ef6e905094fca6e3e90af7549a69e3e8a43876c9e /home/user/projectdir/.lvimrc

The version field will allow making changes to the format of the file (for instance changing the default hash function). The metadata contains the SHA-256 hash of the file. I chose a different format because a) Having the filename at the end of the line makes it easy to store filenames with special characters and `:` is better for parsing (also, Vim's modeline uses it).

The only problem is that `sha256sum` or other utility (for example Python with crypto lib) may not be present on the system. In that case the plugin could fall back to using a `mtime` field (`mtime=1515086833`) but not by default.

For extra paranoid security: The plugin should create private copy in a temporary directory of every `.lvimrc` file it's going to source, and source it after it successfully validates its hash. The file on a filesystem can change between validating its hash and sourcing it. For example it may be on a Samba shared folder. Temporary directories are memory backed on contemporary distros and rc files are generally small.

**Comment by embear** [comment]
> The only problem is that sha256sum or other utility (for example Python with crypto lib) may not be present on the system.

This is exactly the reason why I decided to use this poor man checksum. I don't want to introduce a dependency to an external program for such an simple plugin. Possibly a simple and efficient hash function can be implemented in pure vim script.

**Comment by marak8** [comment]
I fully understand. Though veryfing integrity of sourced files which can execute any code under user's account should be paramount even for a simplest plugin IMO (user isn't warned when poor checksum doesn't change). In any case, I'm not asking you to undertake the effort. I'd like to look at it when I get time.

**Comment by embear** [comment]
You are right that the execution of any code might be a problem. Thats why `sandbox` is enabled by default so there should no harmful code be executed. Maybe I should add an information to the README about this.

I also thought about a better hash algorithm before but had no time to evaluate this. I had in mind to use something like [Fowler–Noll–Vo hash function](https://en.wikipedia.org/wiki/Fowler–Noll–Vo_hash_function). This might be simple enough to be implemented in pure vimscript and secure enough to make it hard to inject code. But I have no idea how long the calculation will take in vimscript. Possibly the implementation could be done in embedded python code for speed.... the calculation of the checksum might happen very often depending on the value of `g:localvimrc_event`

**Comment by embear** [comment]
@marak8 are you still interested in getting more secure checksums? I just added FNV hash with commit bd5c71304bccf256239ead2bea50c3640941f364
As said it is not a cryptographic checksum but it is easy to implement in Python with a VimL fallback and it is better than the previous one.

**Comment by marak8** [comment]
@embear That is awesome! But since you already used python for implementing FNV, I guess you could `import hashlib` and use SHA directly (it's standard library).

**Comment by embear** [comment]
You are right. Now calculation priority is:
1. VIM builtin SHA256
2. Python hashlib SHA256
3. FNV fallback implemented in VimL

**Comment by embear** [comment]
New version released with sha256 checksums, closing this issue
