### ISSUE TITLE
autocmd are not called

### ISSUE THREAD

**Issue by zacharied** [embear/vim-localvimrc#63]
I am unable to set up an autocmd with the `LocalVimRCPre` or `LocalVimRCPost` commands.

Sample configuration:

```vim
" ...after plug#begin()
Plug 'embear/vim-localvimrc'
autocmd LocalVimRCPost echom 'loaded local vimrc'
```

Output:

```
Error detected while processing <REDACTED>:
line  132:
E216: No such group or event: LocalVimRCPost echom 'loaded local vimrc'
```

**Comment by embear** [comment]
Autocommands are working but are not well documented. A plugin is only able to emit `User` events of different types. I added an example to [README](https://github.com/embear/vim-localvimrc#autocommands). Hope that helps.

**Comment by zacharied** [comment]
Wow, that's a part of vim I never knew about. Thanks.

**Comment by philgyford** [comment]
Can you give another example of how to use this other than doing `echom`?

Maybe I'm being stupid, but if I want to use this in my `.lvimrc`:

    autocmd FileType text setlocal textwidth=300 colorcolumn=300

how do I do that? This (or the Pre version) doesn't seem to have any effect:

    autocmd User LocalVimRCPost autocmd FileType text setlocal textwidth=300 colorcolumn=300

Thanks.

**Comment by philgyford** [comment]
Can you give another example that isn't using `echom`?

Maybe I'm misunderstanding something obvious but if I want to use this in my `.lvimrc`:

    autocmd FileType text setlocal textwidth=300 colorcolumn=300

I'm not sure how. On its own it does nothing and this (or its Pre version) also has no effect:

    autocmd User LocalVimRCPost autocmd FileType text setlocal textwidth=300 colorcolumn=300

Thanks.

**Comment by embear** [comment]
You don't need to install autocommands in `.lvimrc`. In fact `.lvimrc` is evaluated by an autocommand. So if you want to emulate something like the above example you can use the mechanism explained [here](https://github.com/embear/vim-localvimrc#modeline-settings-are-overwritten-by-local-vimrc). For your example the `.lvimrc` sould contain
```
if &filetype == "text"
  setlocal textwidth=300 colorcolumn=300
endif

```

**Comment by philgyford** [comment]
Thank you! I missed that or didn't fully understand it. It's now working fine.
