### ISSUE TITLE
Add an option to source local vimrc on startup, before BufWinEnter

### ISSUE THREAD

**Issue by tbodt** [embear/vim-localvimrc#64]
I have Neomake set up to run on BufWinEnter, and my .lvimrc does some Neomake configuration. Since the order of BufWinEnter autocommand execution is not well defined, the .lvimrc gets sourced *after* Neomake runs, so it doesn't use the configuration in .lvimrc.

**Comment by embear** [comment]
Why not just change the setting `g:localvimrc_event`? The following setting in your `.vimrc` or `init.vim` should do the trick:
```
let g:localvimrc_event = [ "BufRead" ]
```
`BufRead` is executed before `BufWinEnter`. You can also trigger localvimrc on two events.
```
let g:localvimrc_event = [ "BufWinEnter", "BufRead" ]
```
This might be useful if you want to change window settings in the local configuration.

**Comment by tbodt** [comment]
Huh, didn't think of BufRead. That works pretty well for me.
