### ISSUE TITLE
Breaking Python Loading Sequence

### ISSUE THREAD

**Issue by cryptoeraser** [embear/vim-localvimrc#69]
Hi,

I have noticed that if none of the plugins that are loading before `vim-localvimrc` are not invoking `py2`, `vim-localvimrc` chooses to invoke `py3`. This breaks any of the plugins that still rely on `py2` and are being loaded after `vim-localvimrc`.

Could you please add an option for explicitly setting the python version to `py2`. The option can be `empty` by default and users who would still rely on `py2` can use that entry point to set the python to `2.x`.

Thanks.

**Comment by embear** [comment]
I just pushed a commit that should fix the problems. It does

1. It does check for python versions only if there is no `sha256` function built into Vim itself.
2. It checks only for enabled python versions. Checks are enabled by default but can be disabled via `g:localvimrc_python2_enable` and `g:localvimrc_python3_enable`

**Comment by cryptoeraser** [comment]
Thanks for looking into this in such a short time. I will give it a try.

**Comment by embear** [comment]
Seems to be fixed as there was no feedback.
