### ISSUE TITLE
Autoload verified files only

### ISSUE THREAD

**Issue by bew** [embear/vim-localvimrc#71]
Hello, is there a way to auto load (on vim's startup) only verified files from persistent file?

(from the docs it seems it's not possible)

**Comment by embear** [comment]
No, this is not possible at the moment. I don't know if this will be very useful anyway. The files need to be added to the persistent file by loading them (silently or after the user has been asked). Currently there is no other way to add them.
For loading only verified files there needs to be a separate command to explicitly add them to the persistence file which is also not available at the moment.
