### ISSUE TITLE
Advantages of localvimrc over exrc ?

### ISSUE THREAD

**Issue by Fandekasp** [embear/vim-localvimrc#75]
Hi,

I just came across your project, and couldn't find a comparison with the core `exrc` option. Can you highlight the differences?

**Comment by embear** [comment]
Main difference is that not the current directory is searched but the filesystem tree of the edited file regardless of the current directory. Depending on settings all localvimrc files are sourced up to the filesystem root or down the tree to the edited file. You can distribute your favorite settings with the source code. It is more comparable to [Editorconfig](https://editorconfig.org) than to exrc. Editorconfig is cross editor but with very limited feature set while localvimrc is Vim only but allows much more configuration i.e. setting `makeprg`.

**Comment by Fandekasp** [comment]
Thanks for the explanation!
