### ISSUE TITLE
Syntax error in catch clause

### ISSUE THREAD

**Issue by silvioricardoc** [embear/vim-localvimrc#77]
The following line in localvimrc.vim generates a syntax error:
```vim
catch ^Vim\%((\a\+)\)\=:E48
```

The correct syntax should include delimiters:
```vim
catch /^Vim\%((\a\+)\)\=:E48/
```

(This is seen in Neovim v0.4.3. Maybe vim itself is a bit more lax on the syntax?)

**Comment by embear** [comment]
This bug has been fixed quite some time ago. Latest releases on [github](https://github.com/embear/vim-localvimrc/releases/tag/v3.1.0) and [www.vim.org](https://www.vim.org/scripts/script.php?script_id=441) already contain this change.
