### ISSUE TITLE
LocalVimRCMatchAny: No previous substitute regular expression

### ISSUE THREAD

**Issue by ntessore** [embear/vim-localvimrc#80]
Thanks for this great plugin! When opening a file affected by a `.lvimrc` file, I am seeing the following error:

```
<SNR>34_LocalVimRCMatchAny:
line    2:
E33: No previous substitute regular expression
Press ENTER or type command to continue
```

The plugin recovers well and everything else appears to work.

Vim version:

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 19 2020 21:23:05)
macOS version
Included patches: 1-2164
Compiled by root@Mac-1608412769109.local
Huge version with MacVim GUI.  Features included (+) or not (-):
```

**Comment by embear** [comment]
Hard to say what is the problem as you gave very little informations. From the location of the error I suspect that there might be something wrong with `localvimrc_whitelist` or `localvimrc_blacklist` or some special characters in the path to your `.lvimrc`.

If you feel comfortable with sending debug data that would also help. For that increase the debug level with `let g:localvimrc_debug = 99` in your VIMRC and paste the output of `:LocalVimRCDebugShow` here.

**Comment by ntessore** [comment]
It was a bad entry in `localvimrc_whitelist` that used `~` for the home path, and I didn't make the connection. Perhaps there is a way to catch and ignore the error, in case it confuses others. Anyway, thanks for fixing this so quickly.

**Comment by embear** [comment]
Good point. I think I'll add a try/catch block with a more helpful message.
