### ISSUE TITLE
how to avoid manually loading .lvimrc

### ISSUE THREAD

**Issue by laoshaw** [embear/vim-localvimrc#81]
put `let g:localvimrc_enable=1` into $HOME/.vimrc and .lvimrc still each time I open a new file it's asking me to manually to load .lvimrc, how can I load it automatically? tested on ubuntu 20.04.

**Comment by embear** [comment]
There is a setting `g:localvimrc_ask` which is set to `1` by default for security reasons. To prevent asking you need to set it to `0`. Possibly you also need to set `g:localvimrc_sandbox` to `0`, if you use commands that are not allowed in a sandbox environment. 
Please see `:he g:localvimrc_ask` and `:he g:localvimrc_sandbox` for more information.
