### ISSUE TITLE
Config Doesn't Load When Event Is Set To `VimEnter`

### ISSUE THREAD

**Issue by Rican7** [embear/vim-localvimrc#82]
Hi! This project is fantastic!

I noticed an issue, however... when setting `let g:localvimrc_event = [ 'VimEnter' ]`, local VIM configs are never loaded.

I've tried a lot of different events, with them all working correctly, except for `VimEnter`. 🤔 😕

**Comment by embear** [comment]
Localvimrc is intended to load settings for every buffer you are editing. So the settings can only be loaded if an actual buffer is loaded and the plugin is able to determine the location of the file.
Additionally the localvimrc plugin reads potentially different .lvimrc, if the edited files are located in different filesystem locations/projects. 
From where should the plugin load the .lvimrc file in your case? The current working directory? The path NERD tree tries to load? Another file you gave at the command line? 

The possibility to change the event is intended for example to read only when a buffer is read or every time it is shown in a new window etc.

If you want to apply settings only once from a .lvimrc file I'd recommend to use the variables `g:localvimrc_sourced_once` and `g:localvimrc_sourced_once_for_file` and add the following to the .lvimrc file:

```
" guard to end loading if it has been loaded for the running vim instance
if g:localvimrc_sourced_once
  finish
endif

" do stuff you want to do only once for a running vim instance
```

**Comment by Rican7** [comment]
> Localvimrc is intended to load settings for every buffer you are editing.

While I see that the way its implemented does seem to imply that, the project description and details never seemed to indicate that, so sorry if I misunderstood the project's goals.

I was hoping to use this for a per-project (project root directory) Vim configuration.

> From where should the plugin load the .lvimrc file in your case? The current working directory? The path NERD tree tries to load? Another file you gave at the command line?

Yea, my thought was that it would load from the directory where I started Vim, especially if Vim was started without an initial file (just a bare `vim` command). I could see how it would make sense to maybe check the path of a passed file too, but honestly I just figured it'd work based on Vim's built-in [`current-directory`](https://vimhelp.org/editing.txt.html#current-directory), so that it worked well with other expectations in Vim (and other plugins).

> The possibility to change the event is intended for example to read only when a buffer is read or every time it is shown in a new window etc.

Yea, and that makes sense. I just thought it was a bit of a confusing/surprising behavior to just not run on `VimEnter` due to being focused on a typed buffer, even though the event is supported. No message of why or anything.

**Comment by embear** [comment]
> While I see that the way its implemented does seem to imply that, the project description and details never seemed to indicate that, so sorry if I misunderstood the project's goals.

Quote from the first sentence in the README.md / Vim helpfile:

 > This plugin searches for local vimrc files in the file system tree of the currently opened file.

By using the above code snippet you get exactly the behavior you want. Possibly I should add another remark in the section describing the `g:localvimrc_event` setting that not all available events make sense.

**Comment by Rican7** [comment]
Hmm, yea. This is all fair.

I guess it'd be nice if there was a configuration for this behavior, rather than the hard-stop of processing being hard-coded.
