### ISSUE TITLE
make fails due to outdated BeautifulSoup package

### ISSUE THREAD

**Issue by fischerjd** [embear/vim-localvimrc#83]
After cloning your repository and installing the required Python3 software, when I invoke 'make' the build fails with the following error message,

> "You're trying to run a very old release of Beautiful Soup under Python 3. This will not work."<>"Please use Beautiful Soup 4, available through the pip package 'beautifulsoup4'."

See also: [build.log](https://github.com/embear/vim-localvimrc/files/7491236/build.log)

**Comment by embear** [comment]
Actually the makefile is not meant to be used by a normal user but by me when preparing a release. The error you get is actually caused by the html2vimdoc converter.
As a user of the plugin you actually just need to copy the plugin and doc directory.
