### ISSUE TITLE
Propose for a licence

### ISSUE THREAD

**Issue by MikeWalrus** [embear/vim-localvimrc#85]
Amazing plugin!

It would be really nice if a license is included. Maybe [choose a license](https://choosealicense.com/)?

**Comment by embear** [comment]
localvimrc is already licensed under the terms of GPL v3. The license notice is included in the plugin source. To make the license more visible I added the full license file in commit b0a81e42e6036f716bd9e6b025978dfb7dacaa53

**Comment by MikeWalrus** [comment]
Thanks! I’ve missed the notice in the source.
:)
